services:
  mongo:
    image: mongo:8.0.8
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - INTERNAL_PORT=${INTERNAL_BACKEND_PORT}
      - DB_HOST=mongo
      - DB_PORT=27017
      - ALLOWED_ORIGINS=http://localhost:4200,http://localhost:4444
    env_file:
      - ./backend/.env 
    ports:
      - "3333:${INTERNAL_BACKEND_PORT}"
    depends_on:
      - mongo
    volumes:
      - ./backend/src:/app/src
      - ./backend/pyproject.toml:/app/pyproject.toml
      - ./backend/poetry.lock:/app/poetry.lock
    command: uvicorn src.main:app --host 0.0.0.0 --port ${INTERNAL_BACKEND_PORT} --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    environment:
      - INTERNAL_PORT=${INTERNAL_FRONTEND_PORT}
    env_file:
      - ./frontend/.env
    ports:
      - "4444:${INTERNAL_FRONTEND_PORT}"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: npm run start -- --port=${INTERNAL_FRONTEND_PORT} --host=0.0.0.0

volumes:
  mongo-data:
