site_name: Agile Wheel Documentation
site_url: http://localhost:8009

docs_dir: docs

nav:
  - Home: index.md
  - Backend: backend/index.md
  - Frontend: frontend/index.md

theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
