site_name: Agile Wheel Documentation

docs_dir: docs

site_url: https://miguelsmuller.github.io/agile-wheel/
repo_url: https://github.com/miguelsmuller/agile-wheel

nav:
  - Introduction:
    - Framework Agile Wheel: README.md
    - Automations: automations.md
    - Running Locally: local-run.md
    - Other Topics: others.md
  
  - Architecture:
    - Architecture Overview: 1-architecture/README.md
    - Data Model: 1-architecture/data-model.md

  - Backend:
    - Backend Overview: 2-backend/README.md
    - Backend Configuration: 2-backend/configuration.md
    - Domain - Activity:
      - Endpoints HTTP:
        - "[post] Activity Close": 2-backend/triggers/http_post_activity_close.md
      - Endpoints WS: 2-backend/domain-activity-ws.md 

  - Frontend:
    - Frontend Overview: 3-frontend/README.md
    - UI Styling and Theming: 3-frontend/ui-styling-theming.md
    - Page Components:
      - Create Activity: 3-frontend/component-activity-creation-entry.md
      - Join Activity: 3-frontend/component-activity-creation-join.md
      - Activity: 3-frontend/component-activity.md
      - Result: 3-frontend/component-result.md
    - Frontend Services and Data Flow: 3-frontend/frontend-services-data-flow.md

  - Deployment:
    - Deployment Overview: 4-development-deployment/README.md
    - Docker Setup: 4-development-deployment/docker-setup.md
    - Continuous Integration (CI): 4-development-deployment/continuous-integration.md


theme:
  name: material
  palette:
    scheme: default
    primary: black
    accent: indigo
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.path # Dosen't work
    - navigation.expand
    - content.code.copy
    - navigation.footer
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/solid/earth-americas
      link: https://github.com/miguelsmuller/
    - icon: fontawesome/brands/github
      link: https://github.com/miguelsmuller/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/miguelsmuller/

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.snippets:
      base_path: [.] 
      restrict_base_path: false 
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
