name: Deploy Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  frontend:
    name: Frontend Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar dependências
        working-directory: frontend
        run: |
          npm ci

      - name: Generate environment file
        working-directory: frontend
        run: |
          npm run prebuild

      - name: Lint
        working-directory: frontend
        run: |
          npm run lint

      - name: Tests
        working-directory: frontend
        run: |
          npm run test:ci

      - name: Upload cobertura
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage/lcov.info

  sonarcloud-frontend:
    name: SonarCloud Frontend
    runs-on: ubuntu-latest
    needs: frontend

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage

      - name: Análise SonarCloud Frontend
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: frontend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
