name: Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  backend-deploy:
    name: Lint, Test & Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'

      - name: Instalar Poetry
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Instalar dependências
        working-directory: backend
        run: |
          poetry install

      - name: Lint
        working-directory: backend
        run: |
          poetry run ruff check

      - name: Tests
        working-directory: backend
        run: |
          poetry run pytest --cov=src --cov-report=xml

      - name: Deploy do Backend
        working-directory: backend
        run: |
          echo "🚀 Iniciando deploy do Backend"
