name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'

      - name: Instalar Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Instalar dependências do projeto
        run: |
          poetry install

  # The jobs are identical at this point except for the test execution step.
  # I will revisit this in the future to optimize or refactor as needed.
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'

      - name: Instalar Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Instalar dependências do projeto
        run: |
          poetry install

      - name: Executar testes
        run: |
          poetry run pytest --cov=src --cov-report=term --cov-report=html